apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ./appset.yaml

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: ApplicationSet
    patch: |-
      - op: replace
        path: /spec/template/spec/source/path
        value: csdp/managed/{{path.basenameNormalized}}
