apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/codefresh-io/argo-cd/component-field/manifests/install.yaml
  - default-rbac.yaml
images:
  - name: quay.io/codefresh/argocd
    newTag: component-field

# will be effective on argo-cd 2.1
configMapGenerator:
  - behavior: merge
    literals:
      - timeout.reconciliation=20s
      - accounts.admin=apiKey,login
    name: argocd-cm
  - behavior: merge
    literals:
      - server.insecure=true
    name: argocd-cmd-params-cm

    # reset the crbs to `subject.namespace: default`, so that argo-cd will later change them to the actual ns
patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: default
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      version: v1
