global:
  # Controlls argo-cd image
  image:
    repository: quay.io/codefresh/argocd
    tag: v2.1.14-cap-CR-10462

argo-cd:
  fullnameOverride: "argocd"
  server:
    extraArgs:
      - --insecure
    configEnabled: true
    config:
      accounts.admin: apiKey,login
      timeout.reconciliation: 20s

  notifications:
    # -- Enable Notifications controller
    enabled: false

  applicationSet:
    enable: true
    image:
      # -- Repository to use for the application set controller
      repository: quay.io/argoproj/argocd-applicationset
      # -- Image pull policy for the application set controller
      pullPolicy: IfNotPresent
      # -- Tag to use for the application set controller
      tag: "v0.4.1"
