apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: codefresh-cm
    behavior: create
    literals:
      - version=v0.0.318
